---
# Rubyインストールに必要なパッケージをインストール
- name: Install ruby package
  become: yes
  yum:
    state: present
    name: 
      - git
      - make
      - gcc-c++
      - patch
      - openssl-devel
      - libyaml-devel
      - libffi-devel
      - libicu-devel
      - libxml2
      - libxslt
      - libxml2-devel
      - libxslt-devel
      - zlib-devel
      - readline-devel
      - ImageMagick-devel

- name: check rbenv install # rubyのバージョン管理ツールであるrbenvがインストールされているか確認
  shell: bash -lc "rbenv --version"
  register: rbenv_exists
  changed_when: no
  ignore_errors: yes # タスクがエラーになった場合でも、スクリプトの実行を中断せずに続行させる

- name: Install rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: /home/ec2-user/.rbenv
  when: rbenv_exists is failed

- name: Add rbenv to PATH
  lineinfile: # ファイルないの特定の行に変更を加えるためのモジュール
    path: /home/ec2-user/.bash_profile
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: Enable shims and autocompletion for rbenv
  lineinfile:
    path: /home/ec2-user/.bash_profile
    line: 'eval "$(rbenv init -)"'

- name: Reload bash profile
  shell: source /home/ec2-user/.bash_profile

- name: Install ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: /home/ec2-user/.rbenv/plugins/ruby-build

- name: Check ruby installed
  shell: bash -lc "rbenv versions | grep {{ ruby_version }}"
  register: ruby_check_install
  changed_when: no
  ignore_errors: yes

- name: Install Ruby
  shell: bash -lc "rbenv install {{ ruby_version }}"
  when: ruby_check_install is failed

- name: Set default Ruby version
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"

- name: Install bundler and so on
  shell: bash -lc "gem install {{ item }}"
  with_items:
    - rbenv-rehash
    - bundler -v '{{ bundler_version }}'
    - rails -v '{{ rails_version }}'
