---
- hosts: ansible_client
  remote_user: ec2-user

  vars: 
    app_dir: /home/ec2-user/raisetech-live8-sample-app
    ruby_version: 3.1.2
    bundler_version: 2.3.14
    rails_version: 7.0.4
    node_version: 17.9.1

  roles:
    - rbenv
    - node
    - app-clone
    - mysql
    - nginx
#    - unicorn
    - app-start